# Generated by Django 5.2.5 on 2025-10-26 08:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('company', models.CharField(max_length=300)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField()),
                ('required_skills', models.JSONField(blank=True, default=list)),
                ('experience_level', models.CharField(blank=True, max_length=50)),
                ('job_type', models.CharField(blank=True, max_length=50)),
                ('salary_min', models.IntegerField(blank=True, null=True)),
                ('salary_max', models.IntegerField(blank=True, null=True)),
                ('salary_currency', models.CharField(default='USD', max_length=10)),
                ('posted_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-posted_date', '-created_at'],
                'indexes': [models.Index(fields=['title'], name='jobs_job_title_0e1e41_idx'), models.Index(fields=['company'], name='jobs_job_company_73ae7f_idx'), models.Index(fields=['is_active'], name='jobs_job_is_acti_b6ae73_idx')],
            },
        ),
        migrations.CreateModel(
            name='JobMatchScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_score', models.FloatField(help_text='Similarity score from 0 to 100')),
                ('matched_skills', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.job')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-match_score', '-created_at'],
                'unique_together': {('user', 'job')},
            },
        ),
    ]
