# Generated by Django 5.2.5 on 2025-10-21 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_cvtemplate_alter_passwordresettoken_expires_at_and_more"),
    ]

    operations = [
        migrations.RunSQL(
            # Add unique constraint for email field
            "CREATE UNIQUE INDEX IF NOT EXISTS auth_user_email_unique ON auth_user (email) WHERE email != '';",
            # Reverse operation (remove the constraint)
            "DROP INDEX IF EXISTS auth_user_email_unique;",
        ),
    ]
