# Generated by Django 5.2.5 on 2025-11-28 18:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_add_unique_email_constraint'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usercv',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AddField(
            model_name='usercv',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usercv',
            name='name',
            field=models.CharField(default='My CV', max_length=200),
        ),
        migrations.AddField(
            model_name='usercv',
            name='profile_photo',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='usercv',
            name='projects',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='usercv',
            name='template_choice',
            field=models.CharField(default='classic', max_length=20),
        ),
        migrations.AddField(
            model_name='usercv',
            name='version',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='usercv',
            name='education',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='usercv',
            name='experience',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='usercv',
            name='personal_info',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='usercv',
            name='skills',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='usercv',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.cvtemplate'),
        ),
        migrations.AlterUniqueTogether(
            name='usercv',
            unique_together={('user', 'name', 'version')},
        ),
    ]
